services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: ${TZ:-America/Los_Angeles}
    container_name: Final-sandbox
    shm_size: 2g
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    environment:
      TF_CPP_MIN_LOG_LEVEL: "1"
